// Code generated by "stringer -type blockID,gameState -linecomment -output ui_string.go"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[I-0]
	_ = x[J-1]
	_ = x[L-2]
	_ = x[O-3]
	_ = x[S-4]
	_ = x[T-5]
	_ = x[Z-6]
}

const _blockID_name = "IJLOSTZ"

var _blockID_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7}

func (i blockID) String() string {
	if i >= blockID(len(_blockID_index)-1) {
		return "blockID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _blockID_name[_blockID_index[i]:_blockID_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[gameNone-0]
	_ = x[gameRunning-1]
	_ = x[gameFullLines-2]
	_ = x[gameLineAnim-3]
	_ = x[gamePaused-4]
	_ = x[gameOver-5]
	_ = x[gameLeft-6]
}

const _gameState_name = "NOSTATERUNNINGFULLLINESLINEANIMPAUSEDGAME OVERGAMELEFT"

var _gameState_index = [...]uint8{0, 7, 14, 23, 31, 37, 46, 54}

func (i gameState) String() string {
	if i >= gameState(len(_gameState_index)-1) {
		return "gameState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _gameState_name[_gameState_index[i]:_gameState_index[i+1]]
}
